# Generated by Django 4.2.1 on 2024-07-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='substrate',
        ),
        migrations.AddField(
            model_name='substrate',
            name='Layers',
            field=models.ManyToManyField(to='samples.layercomposition'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='layercomposition',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
