# Generated by Django 4.2.1 on 2024-07-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_remove_layer_substrate_substrate_layers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='Symbol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
