# Generated by Django 4.2.1 on 2024-07-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_element_symbol_alter_element_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substrate',
            name='Layers',
            field=models.ManyToManyField(to='samples.layer'),
        ),
    ]
