# Generated by Django 4.2.1 on 2024-07-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_alter_substrate_layers'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermachinemodel',
            name='firstName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usermachinemodel',
            name='lastName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
