# Generated by Django 4.2.1 on 2024-07-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0006_usermachinemodel_firstname_usermachinemodel_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='thickness',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
