# Generated by Django 4.2.1 on 2024-07-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_layerthickness_alter_substrate_layers'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='File/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='semmodel',
            name='file',
            field=models.ManyToManyField(blank=True, to='samples.file'),
        ),
    ]
