# Generated by Django 4.2.1 on 2024-07-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0011_file_user_alter_file_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semmodelfile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='semmodelfile',
            name='my_model',
        ),
    ]
