# Generated by Django 4.2.1 on 2024-07-25 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0012_remove_semmodelfile_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SEMModelFile',
        ),
    ]
