# Generated by Django 4.2.1 on 2024-08-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0015_afmmodel_method_semmodel_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afmmodel',
            options={'verbose_name': 'afm', 'verbose_name_plural': 'afms'},
        ),
        migrations.AlterField(
            model_name='afmmodel',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='semmodel',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
