# Generated by Django 4.2.1 on 2024-08-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0016_alter_afmmodel_options_alter_afmmodel_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplemodel',
            old_name='user',
            new_name='user_machine',
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
