# Generated by Django 4.2.1 on 2024-08-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0017_rename_user_samplemodel_user_machine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substrate',
            name='Layers',
            field=models.ManyToManyField(blank=True, null=True, to='samples.layerthickness'),
        ),
    ]
