# Generated by Django 4.2.1 on 2024-08-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0019_alter_substrate_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerthickness',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='layerthickness',
            name='thickness',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
