# Generated by Django 4.2.1 on 2024-08-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0020_alter_layerthickness_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='file/'),
        ),
        migrations.AlterField(
            model_name='substrate',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
