# Generated by Django 4.2.1 on 2024-08-21 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0021_alter_file_file_alter_substrate_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substrate',
            name='Layers',
            field=models.ManyToManyField(to='samples.layerthickness'),
        ),
        migrations.AlterField(
            model_name='substrate',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
