# Generated by Django 4.2.1 on 2024-08-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0022_alter_substrate_layers_alter_substrate_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substrate',
            name='Layers',
            field=models.ManyToManyField(blank=True, null=True, to='samples.layerthickness'),
        ),
    ]
