# Generated by Django 4.2.1 on 2024-08-22 15:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samples', '0023_alter_substrate_layers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afmmodel',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='afmmodel',
            name='file',
            field=models.ManyToManyField(blank=True, null=True, to='samples.file'),
        ),
        migrations.AlterField(
            model_name='afmmodel',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samples.samplemodel'),
        ),
        migrations.AlterField(
            model_name='file',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='layer',
            name='doped',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.element'),
        ),
        migrations.AlterField(
            model_name='layercomposition',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samples.element'),
        ),
        migrations.AlterField(
            model_name='layerthickness',
            name='Layers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.layer'),
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='prev_sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.samplemodel'),
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='substrate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.substrate'),
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='user_machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samples.usermachinemodel'),
        ),
        migrations.AlterField(
            model_name='semmodel',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='semmodel',
            name='file',
            field=models.ManyToManyField(blank=True, null=True, to='samples.file'),
        ),
        migrations.AlterField(
            model_name='semmodel',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samples.samplemodel'),
        ),
        migrations.AlterField(
            model_name='usermachinemodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
