# Generated by Django 4.2.1 on 2024-08-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0024_alter_afmmodel_created_at_alter_afmmodel_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='group',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
